name: sqlite_async
description: High-performance asynchronous interface for SQLite on Dart and Flutter.
version: 0.6.0
repository: https://github.com/powersync-ja/sqlite_async.dart
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  sqlite3: '^2.3.0'
  async: ^2.10.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  test_api: ^0.7.0
  glob: ^2.1.1
  benchmarking: ^0.6.1
