name: sqlite_async
description: High-performance asynchronous interface for SQLite on Dart and Flutter.
version: 0.5.1
repository: https://github.com/journeyapps/sqlite_async.dart
environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  sqlite3: '>=1.10.1 <3.0.0'
  async: ^2.10.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_api: ^0.4.18
  glob: ^2.1.1
  benchmarking: ^0.6.1
